// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCizT7m0KSivChl4_V2usfGD-V88YysH2g',
    appId: '1:823408518388:web:ecdb0f0ba391db436eaaa1',
    messagingSenderId: '823408518388',
    projectId: 'abrarnoteapp',
    authDomain: 'abrarnoteapp.firebaseapp.com',
    storageBucket: 'abrarnoteapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ6kIW-0Yo4p4cWLBM6YsxLFVCqUwgGFw',
    appId: '1:823408518388:android:4daf2dd8fddc440b6eaaa1',
    messagingSenderId: '823408518388',
    projectId: 'abrarnoteapp',
    storageBucket: 'abrarnoteapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXertqeyc6VtCe_jthFafsrpesXuLFaxQ',
    appId: '1:823408518388:ios:97243253b57fd5436eaaa1',
    messagingSenderId: '823408518388',
    projectId: 'abrarnoteapp',
    storageBucket: 'abrarnoteapp.appspot.com',
    iosClientId: '823408518388-3bqtuh3umv4q3njrt8035gqss74rivtu.apps.googleusercontent.com',
    iosBundleId: 'com.abrar.abrar',
  );
}
